Make ProductInstances lazy so derivation works for recursive types
typelevel/shapeless-3 pull request #47
Opened 2021-11-03 11:12 UTC by TimWSpence

2021-11-03 11:13 UTC, TimWSpence commented
Compilation hangs on that new test case if I remove the `=>` so it seems to work as expected

2021-11-03 11:23 UTC, joroKr21 commented
We need to think about whether we can break binary compatibility here - those classes are considered internal, but there is a lot of inlining happening here and I'm not sure.

2021-11-03 11:25 UTC, TimWSpence commented
> We need to think about whether we can break binary compatibility here - those classes are considered internal, but there is a lot of inlining happening here and I'm not sure.

Mima seems to think that it will break bincompat. Not sure if there's anything we can do about that? I also can't figure out where the version is defined if we do want to bump the major version 😂

2021-11-03 11:27 UTC, joroKr21 commented
We definitely don't want to bump the major version 😄 - but those classes are in the `internals` package because they are not supposed to be used directly by users. So we could just ignore this package from MiMa checks. I'm just not 100% convinced that it wouldn't cause issues anyway because of inlining.

2021-11-03 11:30 UTC, milessabin commented
LGTM apart from the major version bump!

2021-11-03 11:30 UTC, TimWSpence commented
> We definitely don't want to bump the major version 😄 - but those classes are in the `internals` package because they are not supposed to be used directly by users. So we could just ignore this package from MiMa checks. I'm just not 100% convinced that it wouldn't cause issues anyway because of inlining.

Good question, I'm not sure of the impact of inlining.

Do we have any idea how many projects are currently depending on shapeless 3 and hence affected if we ever did break bincompat?

2021-11-03 11:42 UTC, TimWSpence commented
> We definitely don't want to bump the major version 😄 - but those classes are in the `internals` package because they are not supposed to be used directly by users. So we could just ignore this package from MiMa checks. I'm just not 100% convinced that it wouldn't cause issues anyway because of inlining.

🤦 I hadn't realized that that version is the only thing distinguishing this from shapeless 2! I thought we were publishing a separately versioned shapeless 3 artifact but we're not

2021-11-03 12:19 UTC, joroKr21 commented
The organisation is also different. But no I'm not aware of the current usage of shapeless. I see that there are already some breaking changes we ignore in the `internals` package. On the other hand it's also possible to make the primary constructor take `() => Array[Any]`, add a secondary constructor which is eager and change the `ErasedProductInstances.apply` method. If we're not sure this would preserve binary compatibility.

2021-11-15 12:30 UTC, TimWSpence commented
@joroKr21 I just set up a test project with a single file (https://gist.github.com/TimWSpence/7083c57567789b717d56cfc4514b1289) and compiled it via sbt using shapeless 3.0.3. I then ran it manually with `java` with an explicit classpath. Swapping shapeless 3.0.3 for a locally published snapshot gives
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void shapeless3.deriving.internals.ErasedProductInstances1.<init>(scala.deriving.Mirror$Product, java.lang.Object)'
        at Main$package$.run(Main.scala:52)
        at run.main(Main.scala:45)

```

😭 So yes, I think inlining does cause bin-compat problems

2021-11-15 12:37 UTC, joroKr21 commented
Thanks for checking @TimWSpence ! Yeah in that case we should go for the binary compatible solution with a secondary constructor.

2021-11-15 15:30 UTC, joroKr21 requested changes
Other than that LGTM - awesome work 👍

2021-11-15 15:30 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/internals/erased.scala
> +  //instances for recursive types
Can we make that the message of `@deprecated`?

2021-11-15 15:30 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/internals/erased.scala
> +  //instances for recursive types
Same here

2021-11-15 15:30 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/internals/erased.scala
> +private[shapeless3] final class ErasedProductInstances1[K, FT](val mirror: Mirror.Product, _i: () => Any) extends ErasedProductInstances[K, FT] {
Just for consistency
```suggestion
private[shapeless3] final class ErasedProductInstances1[K, FT](val mirror: Mirror.Product, i0: () => Any) extends ErasedProductInstances[K, FT] {
```

2021-11-15 15:30 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/internals/erased.scala
> +private[shapeless3] final class ErasedProductInstancesN[K, FT](val mirror: Mirror.Product, _is: () => Array[Any]) extends ErasedProductInstances[K, FT] {
here too:
```suggestion
private[shapeless3] final class ErasedProductInstancesN[K, FT](val mirror: Mirror.Product, is0: () => Array[Any]) extends ErasedProductInstances[K, FT] {
```

2021-11-15 16:02 UTC, joroKr21 approved these changes
Nice!

2021-11-15 16:02 UTC, merged

2021-11-15 16:03 UTC, joroKr21 commented
Should we merge #44 so we can release this?

2021-11-15 16:13 UTC, TimWSpence commented
> Should we merge #44 so we can release this?

Fine by me! So have we never released for 3.1.0?

2021-11-15 16:15 UTC, joroKr21 commented
No we haven't yet