Implementation of issue #55: Implement type annotations
typelevel/shapeless-3 pull request #56
Opened 2021-12-15 23:30 UTC by pgrandjean

2022-01-06 08:54 UTC, joroKr21 commented
Thanks a lot and sorry for the delay - I will try to review this soon, but I didn't forget about it

2022-03-12 07:56 UTC, pgrandjean commented
🙏

2022-04-02 19:06 UTC, pgrandjean commented
rebased

2022-04-09 08:23 UTC, joroKr21 requested changes
Sorry for taking so long to review 🙈 

Overall looks good, the documentation can be improved and some polishing to do.
We should also add some tests with enums - that's the future of ADTs.

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> + * field or constructor) or `HLists` (list of annotations for corresponding field or constructor).
```suggestion
 * Type `Out` is a tuple having the same number of elements as `T` (number of fields of `T` if `T` is a product type,
 * or number of constructors of `T` if it is a sum type). It is made of tuples
 * containing all annotations for the corresponding field or constructor (`EmptyTuple` if none).
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> + * or `HList` (corresponding field or constructor has annotations).
```suggestion
 * Method `apply` provides a tuple of type `Out` made of tuples
 * containing all annotations for the corresponding field or constructor (`EmptyTuple` if none).
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> + * Note that type annotations must be case class-like for this type class to take them into account.
```suggestion
 * Note that type annotations must not be abstract for this type class to take them into account.
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> + *   //   ((), (First("a"), Second(0)))
```suggestion
 *   // ccFirsts.Out is  (EmptyTuple, (First, Second))
 *   // ccFirsts.apply() is
 *   //   (EmptyTuple, (First("a"), Second(0)))
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> + *   //   HNil :: (First("a") :: Second(0) :: HNil) :: HNil
```suggestion
 *   // ccFirsts.Out is  (EmptyTuple, (First, Second)
 *   // ccFirsts.apply() is
 *   //   (EmptyTuple, (First("a"), Second(0))
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> +  def mkAnnotations[A: Type, T: Type](using Quotes): Expr[Annotations[A, T]] = mkAnnotationsImpl[A, T, Annotations](ofExprVariableAnnotations[A, T](_))
```suggestion
  def mkAnnotations[A: Type, T: Type](using Quotes): Expr[Annotations[A, T]] = mkAnnotationsImpl[A, T, Annotations](ofExprVariableAnnotations)
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> +  def mkTypeAnnotations[A: Type, T: Type](using Quotes): Expr[TypeAnnotations[A, T]] = mkAnnotationsImpl[A, T, TypeAnnotations](ofExprTypeAnnotations[A, T](_))
```suggestion
  def mkTypeAnnotations[A: Type, T: Type](using Quotes): Expr[TypeAnnotations[A, T]] = mkAnnotationsImpl[A, T, TypeAnnotations](ofExprTypeAnnotations)
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> +    import q.reflect._
We shouldn't use `Quotes` directly

```suggestion
  private def mkAnnotationsImpl[A: Type, T: Type, AS[A, T]: Type](mk: Seq[Expr[Any]] => Expr[AS[A, T]])(using Quotes): Expr[AS[A, T]] =
    import quotes.reflect._
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> +    // println(s"tpe = ${tpe}")
Stray println

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> +      // println(s"extractAnnotations = \n\t${annotations.mkString("\n\t")}")
Please remove

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> +    // println(s"tpe = ${tpe}")
Please remove

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> +    // println(s"annotations = \n\t${annotations.mkString("\n\t")}")
Please remove

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> +      // println(s"${depth}: ${tree.show(using Printer.TreeStructure)}")
Remove please

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> +    def getAnnotations(tree: Tree, acc: List[Term] = Nil, depth: Int = 0): List[Term] =
Can this be `@tailrec`?

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> +      // println(s"${depth}: typeRepr = ${typeRepr}")
Remove please

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> +          .find(_.headOption.fold(false)( _.isTerm))
```suggestion
          .find(_.exists(_.isTerm))
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> +            report.throwError(s"No Annotations for sum type ${annoteeTpe.show} with no Mirror")
```suggestion
            report.errorAndAbort(s"No Annotations for type ${annoteeTpe.show} without Mirror")
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> +        report.throwError(s"No Annotations for non-class ${annoteeTpe.show}")
```suggestion
        report.errorAndAbort(s"No Annotations for non-class ${annoteeTpe.show}")
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> +  def ofExprVariableAnnotations[A: Type, T: Type](annotTrees: Seq[Expr[Any]])(using q: Quotes): Expr[Annotations[A, T]] =
```suggestion
  def ofExprVariableAnnotations[A: Type, T: Type](annotTrees: Seq[Expr[Any]])(using Quotes): Expr[Annotations[A, T]] =
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> +  def ofExprTypeAnnotations[A: Type, T: Type](annotTrees: Seq[Expr[Any]])(using q: Quotes): Expr[TypeAnnotations[A, T]] =
```suggestion
  def ofExprTypeAnnotations[A: Type, T: Type](annotTrees: Seq[Expr[Any]])(using Quotes): Expr[TypeAnnotations[A, T]] =
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> +  def ofExprAllVariableAnnotations[T: Type](annotTrees: Seq[Expr[Any]])(using q: Quotes): Expr[AllAnnotations[T]] =
```suggestion
  def ofExprAllVariableAnnotations[T: Type](annotTrees: Seq[Expr[Any]])(using Quotes): Expr[AllAnnotations[T]] =
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> +  def ofExprAllTypeAnnotations[T: Type](annotTrees: Seq[Expr[Any]])(using q: Quotes): Expr[AllTypeAnnotations[T]] =
```suggestion
  def ofExprAllTypeAnnotations[T: Type](annotTrees: Seq[Expr[Any]])(using Quotes): Expr[AllTypeAnnotations[T]] =
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/test/scala/shapeless3/deriving/annotation.scala
> +    illTyped(" TypeAnnotations[Second, Dummy] ", "could not find implicit value for parameter annotations: .*")
```suggestion
    illTyped("TypeAnnotations[Dummy, CC2]", "could not find implicit value for parameter annotations: .*")
    illTyped("TypeAnnotations[Dummy, Base]", "could not find implicit value for parameter annotations: .*")
    illTyped("TypeAnnotations[Second, Dummy]", "could not find implicit value for parameter annotations: .*")
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/test/scala/shapeless3/deriving/annotation.scala
> +    type T1First = First *: EmptyTuple.type
```suggestion
    type T1First = First *: EmptyTuple
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/test/scala/shapeless3/deriving/annotation.scala
> +    val cc: (T1First, EmptyTuple.type, (Second, Third)) = AllAnnotations[CC3].apply()
```suggestion
    val cc: (T1First, EmptyTuple, (Second, Third)) = AllAnnotations[CC3].apply()
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/test/scala/shapeless3/deriving/annotation.scala
> +    type T1Second = Second *: EmptyTuple.type
```suggestion
    type T1Second = Second *: EmptyTuple
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/test/scala/shapeless3/deriving/annotation.scala
> +    type T1First = First *: EmptyTuple.type
```suggestion
    type T1First = First *: EmptyTuple
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/test/scala/shapeless3/deriving/annotation.scala
> +    val cc: (T1First, EmptyTuple.type, (Second, Third)) = AllTypeAnnotations[CC4].apply() // case class
```suggestion
    val cc: (T1First, EmptyTuple, (Second, Third)) = AllTypeAnnotations[CC4].apply() // case class
```

2022-04-09 08:23 UTC, joroKr21 commented on modules/deriving/src/test/scala/shapeless3/deriving/annotation.scala
> +    type T1Third = Third *: EmptyTuple.type
```suggestion
    type T1Third = Third *: EmptyTuple
```

2022-04-15 09:45 UTC, joroKr21 commented on modules/deriving/src/main/scala/shapeless3/deriving/annotation.scala
> +    def getAnnotations(tree: Tree, acc: List[Term] = Nil, depth: Int = 0): List[Term] =
Looks like it can't

2022-04-15 21:30 UTC, joroKr21 approved these changes
I addressed my comments - we still need to add more tests but this PR is getting too big.

2022-04-15 21:41 UTC, merged

2022-05-13 19:02 UTC, pgrandjean commented
@joroKr21 thank you for all the fixes and integration!

2022-05-19 00:27 UTC, pgrandjean commented
@joroKr21 what tests need to be added?

2022-05-19 05:52 UTC, joroKr21 commented
> @joroKr21 what tests need to be added?

We were lacking tests with enums - I added one though

2022-05-20 02:07 UTC, pgrandjean commented
I tried using type annotations on enums, but the following syntax is invalid:
```scala
enum Control2:
  case Automatic @First
  case Manual(age: PosInt, email: Email) @Third('!')
```
according to Scala's [EBNF](https://dotty.epfl.ch/docs/internals/syntax.html), the best I can do is:
```scala
enum Control2:
  case Automatic extends Control2 @First
  case Manual(age: PosInt, email: Email) extends Control2 @Third('!')
```
which kills the purpose of the new enum syntax by repeating `extends Control2`. If you see an interest in supporting this syntax, I can add a test.

2022-05-20 06:55 UTC, joroKr21 commented
@pgrandjean this is the test I added:
```scala
@Other @Last(false) enum Control:
    @First @Third('!') case Automatic
    @Second(100, "@") case Manual(age: PosInt, email: Email)
```

Not sure if that corresponds to your expectations. I think you know better than me how this functionality is supposed to be used. More tests can't hurt, but at least we already have one test for sanity check, so if you want to add more it's up to you.

Btw this is not released yet. I got a bit stuck on #36 - wanted to complete it for the next release but it looks still half-baked. I'm thinking of a more useful design so I will leave if for another milestone.